name: LegendaryAlchemy
version: '${project.version}'
main: com.gyzer.lianyao.legendaryalchemy.LegendaryAlchemy
softdepend:
  - DecentHolograms
  - HolographicDisplays
  - PlaceholderAPI
commands:
  lamy: